# CMSE 823 HW 09 Question 3
Anna Stephens, steph496@msu.edu

In [1]:
# LIBRARIES
import pandas as pd
import numpy as np

In [2]:
# Functions to define H and the appropriate b
def getH(n):
    H = np.ones([n,n])
    for i in range(n):
        for j in range(n):
            H[i,j]=1.00/((i+1)+(j+1)-1)
    return(H)

def getb(H):
    x = np.ones(H.shape[0])
    b = np.matmul(H,x)
    return(b)

In [3]:
# (a) LU Decomposition

# Function for LU Decomposition without Pivoting
#  derived from Algorithm 20.1
def luWithoutPivot(A):
    m=A.shape[0]
    U = A
    L=np.identity(m)
    # print('m:',m)
    for k in range(m-1):
        # print(k)
        for j in range(k+1,m):
            # print(' -',j)
            L[j,k] = U[j,k]/U[k,k]
            U[j,k:m] = U[j,k:m] - L[j,k]*U[k,k:m]
    return(L,U)

# Forward Substitution Algorithm
def forwardSub(L,b):
    n = b.shape[0]
    y = np.ones(n) # construct basic y
    for i in range(n):
        c=0
        for j in range(i):
            c+=L[i,j]*y[j]
        y[i] = (b[i]-c)/L[i,i]
    return(y)

# Backward Substitution Algorithm
def backwardSub(U,y):
    n = y.shape[0]
    x = np.ones(n) # construct basic y
    for i in range(n-1,-1,-1):
        # print('i',i)
        c=0
        for j in range(n-1,i,-1):
            # print(' j',j)
            c+=U[i,j]*x[j]
        x[i] = (y[i]-c)/U[i,i]
        # print(i)
    
    return(x)

def solveXLU(n):
    H = getH(n)
    b = getb(H)
    
    L,U=luWithoutPivot(H) # decompose H into L and U
    y = forwardSub(L,b) # use forward substitution to solve for y (Ly=b)
    x = backwardSub(U,y) # use backward substitution to solve for x (Ux=y)
    return(x)

In [4]:
testN = [2,4,6,8,10]

for n in testN:
    print('n:',n)
    x = solveXLU(n)
    
    print(' calculated x:')
    print(x)

n: 2
 calculated x:
[1. 1.]
n: 4
 calculated x:
[1. 1. 1. 1.]
n: 6
 calculated x:
[1. 1. 1. 1. 1. 1.]
n: 8
 calculated x:
[1.         0.99999999 1.00000007 0.9999996  1.00000107 0.99999849
 1.00000108 0.9999997 ]
n: 10
 calculated x:
[1.         1.00000012 0.99999755 1.00002209 0.99989525 1.00028658
 0.99953167 1.00045107 0.99976387 1.0000518 ]


## Comments on Solving for x with LU Decomposition

As the size of the matrix H increased the calculated vector x became increasingly inaccurate.

In [5]:
# (b) Cholesky factorization

# Function for Cholesky Factorization
#  derived from Algorithm 23.1
def cholesky(A):
    m = A.shape[0]
    R = getSuperdiagonalHalf(A)
    for k in range(m):
        for j in range(k+1,m):
            R[j,j:m] = R[j,j:m] - R[k,j:m]*R[k,j]/R[k,k]
        R[k,k:m] = R[k,k:m]/np.sqrt(R[k,k])
    return(R)

def getSuperdiagonalHalf(A):
    new = np.zeros(A.shape)
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            if i<=j: new[i,j] = A[i,j]  
    return (new)

def solveXCholesky(n):
    H = getH(n)
    b = getb(H)
    
    R=cholesky(H) # decompose H into L and U
    y = forwardSub(R.T,b) # use forward substitution to solve for y in Ly=b
    x = backwardSub(R,y) # use backward substitution to solve for x in Ux=y, and therefore Hx=b
    
    return(x)

In [6]:
testN = [2,4,6,8,10]

for n in testN:
    print('n:',n)
    x = solveXCholesky(n)
    print(' calculated x:')
    print(x)

n: 2
 calculated x:
[1. 1.]
n: 4
 calculated x:
[1. 1. 1. 1.]
n: 6
 calculated x:
[1. 1. 1. 1. 1. 1.]
n: 8
 calculated x:
[1.         1.         0.99999996 1.00000021 0.99999943 1.0000008
 0.99999943 1.00000016]
n: 10
 calculated x:
[1.         0.99999967 1.000007   0.99993588 1.00030777 0.99914955
 1.00140133 0.99864087 1.00071574 0.99984218]


## Comments on Solving for x with Cholesky Factorization
Similarly to the LU process above, as the size of the matrix H increased the calculated vector x became increasingly inaccurate.