In [1]:
import numpy as np


import sys
sys.path.append('lib/')
from pca import *

In [2]:
def this_householder(matrix):
    A=matrix.copy().astype(float)
    n=matrix.shape[1]
    v=np.zeros(matrix.shape, float)
    q_star=np.identity(A.shape[0])
    for k in range(n):
        x=A[k:,k]
        v[k:,k]=_getSign(x[0])*np.linalg.norm(x,2)*_getE1(x.shape[0])+x
        # if np.linalg.norm(v[k:,k],2) !=0:v[k:,k]=v[k:,k]/np.linalg.norm(v[k:,k],2) # <--- line throws errors
        if np.linalg.norm(v[k:,k],2)!=0.0: v[k:,k]=v[k:,k]/np.linalg.norm(v[k:,k],2)
        q_k=np.identity(A.shape[0])
        q_k[k:,k:]=_getHV(v[k:,k])
        q_star=np.matmul(q_k,q_star)
        # print(v[k:,k][np.newaxis].T.shape)
        # print(v[k:,k][np.newaxis].shape)
        A[k:,k:]=A[k:,k:]-2*np.matmul(v[k:,k][np.newaxis].T,np.matmul(v[k:,k][np.newaxis],A[k:,k:]))
    
    Q=q_star.T
    R=A.round(8)
    return(Q,R)

def _getHV(v):
    # print('v:',v)
    I=np.identity(v.shape[0])
    Hv = I-2*np.outer(v,v)
    # print('Hv:',Hv)
    return(Hv)

# function that returns an e1 vector of length m
def _getE1(m):
    e1=np.zeros((m))
    e1[0]=1
    return(e1)

# a sign function that checks and corrects for x=0 according to notes in book
def _getSign(x):
    sign=np.sign(x)
    if sign==0: sign=1
    return(sign)

In [3]:
# TRY FOR SOME S
# randomly generate some data matrix X
n = 100 # number of data points
p = 80 # number of features

X = np.random.randint(10,size=(n,p))

X_mean_array = np.mean(X,axis=0)
ones = np.ones(n)
X_mean = np.outer(ones,X_mean_array)
X_diff = X-X_mean
S = np.matmul(X_diff,X_diff.T)/n


H,Q = fullHessenberg(S)
print(H)
print(np.matmul(np.matmul(Q.T,S),Q).round(8))

[[ 7.269329    8.00735523  0.         ...  0.         -0.
  -0.        ]
 [ 8.00735523 15.11341336  6.85508715 ... -0.          0.
  -0.        ]
 [-0.          6.85508715 14.19326462 ... -0.          0.
  -0.        ]
 ...
 [-0.          0.         -0.         ... -0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [-0.          0.         -0.         ... -0.          0.
  -0.        ]]
[[ 7.269329    8.00735523  0.         ... -0.         -0.
  -0.        ]
 [ 8.00735523 15.11341336  6.85508715 ... -0.         -0.
  -0.        ]
 [ 0.          6.85508715 14.19326462 ... -0.         -0.
  -0.        ]
 ...
 [-0.         -0.         -0.         ... -0.          0.
   0.        ]
 [-0.         -0.         -0.         ...  0.          0.
  -0.        ]
 [-0.         -0.         -0.         ...  0.         -0.
   0.        ]]


In [4]:
this_householder(H)

(array([[-0.67216208,  0.38880827, -0.30639081, ...,  0.        ,
          0.        ,  0.        ],
        [-0.74040404, -0.35297238,  0.27815121, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        , -0.85102211, -0.25534821, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  1.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  1.        ]]),
 array([[-10.81484544, -16.57227282,  -5.0755342 , ...,   0.        ,
          -0.        ,  -0.        ],
        [  0.        ,  -8.05512226, -14.49843842, ...,  -0.        ,
           0.        ,  -0.        ],
        [ -0.        ,   0.        ,  -7.26370059, ...,  -0.        ,
           0.        ,  -0.        ],
        ...,
        [ -0.        ,   0.        ,

In [5]:
np.linalg.qr(H)

(array([[-0.67216208,  0.38880827, -0.30639081, ...,  0.        ,
          0.        ,  0.        ],
        [-0.74040404, -0.35297238,  0.27815121, ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        , -0.85102211, -0.25534821, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.        , -0.        ,  0.        , ...,  1.        ,
          0.        ,  0.        ],
        [-0.        , -0.        , -0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 0.        , -0.        ,  0.        , ...,  0.        ,
          0.        ,  1.        ]]),
 array([[-10.81484544, -16.57227282,  -5.0755342 , ...,   0.        ,
          -0.        ,  -0.        ],
        [  0.        ,  -8.05512226, -14.49843842, ...,  -0.        ,
           0.        ,  -0.        ],
        [  0.        ,   0.        ,  -7.26370059, ...,  -0.        ,
           0.        ,  -0.        ],
        ...,
        [  0.        ,   0.        ,