In [2]:
# LIBRARIES
import numpy as np

import sys
sys.path.append('lib/')
from pca import *

In [87]:
def practical_qr_algorithm(matrix,k_max,zero_cutoff):
    m = matrix.shape[0]
    A = np.ones((k_max,m,m),dtype=float)
    A[0] = hessenberg(matrix)
    shift = np.ones(k_max)
    eig=[]
    
    print(matrix.round(5))
    for k in range(1,k_max):
        # print('k:',k)
        shift[k] = A[k-1,m-1,m-1]
        if m==1: 
            # print('last:',shift[k])
            return([shift[k].round(8)])
        Q,R = householder(A[k-1,:,:]-shift[k]*np.identity(m))
        A[k,:,:] = np.matmul(R,Q)+shift[k]*np.identity(m)
        # print(A[k,:,:].round(5))
        for j in range(m-1):
            # print('  j:',j,'val:',A[k,j,j+1])
            if np.abs(A[k,j,j+1]) < zero_cutoff:
                print('shift:',shift[k],',',A[k,j,j+1])
                A[k,j,j+1]=0
                A[k,j+1,j]=0
                # print('shift:',shift[k],',',A[k,j,j+1])
                # break
                A_1 = A[k,:j+1,:j+1]
                A_2 = A[k,j+1:,j+1:]
                # eig=eig+[shift[k].round(8)]
                if A_1.shape[0]>0: 
                    e_temp = practical_qr_algorithm(A_1,k_max,zero_cutoff)
                    # print('eig:',eig,'etemp:',e_temp)
                    if np.abs(e_temp)[0]>0:eig=eig+e_temp
                if A_2.shape[0]>0: 
                    e_temp = practical_qr_algorithm(A_2,k_max,zero_cutoff)
                    # print('eig:',eig,'etemp:',e_temp)
                    if np.abs(e_temp)[0]>0:eig=eig+e_temp
                # return(eig)

    # print('not found')  
    # return(shift[k])
    return(eig)

                

In [88]:
A = np.array(
    [[1,2,3,4],
    [2,1,2,2],
    [3,2,1,3],
    [4,2,3,1]]
)

# A[0,0:A.shape[0]]
print(practical_qr_algorithm(A,20,1e-5))
print(np.linalg.eig(A)[0])

# j=2
# print(A[:j,:j])
# print(A[j:,j:])

[[1 2 3 4]
 [2 1 2 2]
 [3 2 1 3]
 [4 2 3 1]]
shift: -1.7115358725609622 , -1.3162095105215347e-09
[[ 9.15812e+00 -4.55000e-03 -0.00000e+00]
 [-4.55000e-03 -2.95382e+00  3.40280e-01]
 [ 0.00000e+00  3.40280e-01 -4.92770e-01]]
shift: -0.4466024667863122 , -4.878573388611645e-08
[[ 9.15812e+00  3.10000e-04]
 [ 3.10000e-04 -3.00000e+00]]
shift: -3.0 , -9.999999996728529e-09
[[9.15812]]
[[-3.]]
[[-0.44659]]
[[-1.71154]]
[9.15812236, -3.00000001, -0.44658651, -1.71153587]
[ 9.15812238 -3.         -0.4465865  -1.71153588]
