In [1]:
# LIBRARIES
import numpy as np

import sys
sys.path.append('lib/')
from pca import *

In [2]:
def practical_qr_algorithm(matrix,k_max,zero_cutoff):
    m = matrix.shape[0]
    A = np.ones((k_max,m,m),dtype=float)
    A[0],Q_0 = fullHessenberg(matrix)
    shift = np.ones(k_max)
    eigenval=[]
    eigenvect = Q_0
    
    print(matrix.round(5),eigenvect)
    for k in range(1,k_max):
        # print('k:',k)
        shift[k] = A[k-1,m-1,m-1]
        if m==1: 
            # print('last:',shift[k])
            return([shift[k].round(8)],eigenvect)
        Q,R = householder(A[k-1,:,:]-shift[k]*np.identity(m))
        A[k,:,:] = np.matmul(R,Q)+shift[k]*np.identity(m)
        eigenvect = np.matmul(eigenvect,Q)
        # eigenvect = np.matmul(Q,eigenvect)
        if not np.isnan(eigenvect).any():
            print('eigenvect')
            print(eigenvect)
            # print(Q)
        # print(A[k,:,:].round(5))
        
        
        # for j in range(m-1):
        #     # print('  j:',j,'val:',A[k,j,j+1])
        #     if np.abs(A[k,j,j+1]) < zero_cutoff:
        #         print('shift:',shift[k],',',A[k,j,j+1])
        #         A[k,j,j+1]=0
        #         A[k,j+1,j]=0
        #         # print('shift:',shift[k],',',A[k,j,j+1])
        #         # break
        #         A_1 = A[k,:j+1,:j+1]
        #         A_2 = A[k,j+1:,j+1:]
        #         # eig=eig+[shift[k].round(8)]
        #         if A_1.shape[0]>0: 
        #             e_temp = practical_qr_algorithm(A_1,k_max,zero_cutoff)[0]
        #             # print('eig:',eig,'etemp:',e_temp)
        #             if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp
        #         if A_2.shape[0]>0: 
        #             e_temp = practical_qr_algorithm(A_2,k_max,zero_cutoff)[0]
        #             # print('eig:',eig,'etemp:',e_temp)
        #             if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp
        #         # return(eig)

    # print('not found')  
    # return(shift[k])
    # eigenvect = []
    return(eigenval,eigenvect)

# def getEigenvalues(matrix,j):
#     A = matrix.copy().astype(float)
    
    
#                 A[k,j,j+1]=0
#                 A[k,j+1,j]=0
#                 # print('shift:',shift[k],',',A[k,j,j+1])
#                 # break
                # A_1 = A[k,:j+1,:j+1]
                # A_2 = A[k,j+1:,j+1:]
#                 # eig=eig+[shift[k].round(8)]
#                 if A_1.shape[0]>0: 
#                     e_temp = practical_qr_algorithm(A_1,k_max,zero_cutoff)[0]
#                     # print('eig:',eig,'etemp:',e_temp)
#                     if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp
#                 if A_2.shape[0]>0: 
#                     e_temp = practical_qr_algorithm(A_2,k_max,zero_cutoff)[0]
#                     # print('eig:',eig,'etemp:',e_temp)
#                     if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp

In [47]:
def practical_qr_algorithm((matrix,k_max,zero_cutoff)):
    A_0,Q_0 = fullHessenberg(matrix)

def inner(matrix,k_max,zero_cutoff):
    m = matrix.shape[0]
    A = np.ones((k_max,m,m),dtype=float)
    A[0],Q_0 = matrix
    shift = np.ones(k_max)
    eigenval=[]
    eigenvect = Q_0
    
    print(matrix.round(5),eigenvect)
    for k in range(1,k_max):
        # print('k:',k)
        shift[k] = A[k-1,m-1,m-1]
        if m==1: 
            # print('last:',shift[k])
            return([shift[k].round(8)],eigenvect)
        Q,R = householder(A[k-1,:,:]-shift[k]*np.identity(m))
        A[k,:,:] = np.matmul(R,Q)+shift[k]*np.identity(m)
        eigenvect = np.matmul(eigenvect,Q)
        # eigenvect = np.matmul(Q,eigenvect)
        if not np.isnan(eigenvect).any():
            print('eigenvect')
            print(eigenvect)
            # print(Q)
        # print(A[k,:,:].round(5))
        
        
        # for j in range(m-1):
        #     # print('  j:',j,'val:',A[k,j,j+1])
        #     if np.abs(A[k,j,j+1]) < zero_cutoff:
        #         print('shift:',shift[k],',',A[k,j,j+1])
        #         A[k,j,j+1]=0
        #         A[k,j+1,j]=0
        #         # print('shift:',shift[k],',',A[k,j,j+1])
        #         # break
        #         A_1 = A[k,:j+1,:j+1]
        #         A_2 = A[k,j+1:,j+1:]
        #         # eig=eig+[shift[k].round(8)]
        #         if A_1.shape[0]>0: 
        #             e_temp = practical_qr_algorithm(A_1,k_max,zero_cutoff)[0]
        #             # print('eig:',eig,'etemp:',e_temp)
        #             if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp
        #         if A_2.shape[0]>0: 
        #             e_temp = practical_qr_algorithm(A_2,k_max,zero_cutoff)[0]
        #             # print('eig:',eig,'etemp:',e_temp)
        #             if np.abs(e_temp)[0]>0:eigenval=eigenval+e_temp
        #         # return(eig)

    # print('not found')  
    # return(shift[k])
    # eigenvect = []
    return(eigenval,eigenvect)


In [48]:
A = np.array(
    [[1,2,3,4],
    [2,1,2,2],
    [3,2,1,3],
    [4,2,3,1]]
)

# A[0,0:A.shape[0]]
print(practical_qr_algorithm(A,20,1e-5))
print('\n\nNP Results')
npr = np.linalg.eig(A)
print(npr[0])
print(npr[1])

[[1 2 3 4]
 [2 1 2 2]
 [3 2 1 3]
 [4 2 3 1]] [[ 1.          0.          0.          0.        ]
 [ 0.         -0.37139068 -0.69098016 -0.62017367]
 [ 0.         -0.55708601 -0.36852275  0.74420841]
 [ 0.         -0.74278135  0.62188214 -0.24806947]]
eigenvect
[[-0.39830857 -0.78034988 -0.29573678  0.38071525]
 [-0.34065865 -0.23731153  0.89808357 -0.14519235]
 [-0.51098797 -0.00491161 -0.32385078 -0.79623353]
 [-0.6813173   0.57854402 -0.03326143  0.44719933]]
eigenvect
[[ 0.56717998  0.72683116  0.18663955 -0.33939507]
 [ 0.3861233  -0.13695088 -0.90087848 -0.1434267 ]
 [ 0.49840667 -0.00548311  0.07697837  0.86350163]
 [ 0.52991175 -0.67300138  0.38426289 -0.34439035]]
eigenvect
[[-0.54529027 -0.66381309 -0.37429713  0.34915951]
 [-0.39002928 -0.12622607  0.90416026  0.1201597 ]
 [-0.49834898  0.01209135 -0.09882992 -0.86124023]
 [-0.54971262  0.73707053 -0.18063366  0.34916264]]
eigenvect
[[ 0.54763081  0.7381568   0.18252337 -0.3491565 ]
 [ 0.39047256 -0.12289488 -0.90442584 -0.120

In [34]:
A = np.array(
    [[1,2,3,4],
    [2,1,2,2],
    [3,2,1,3],
    [4,2,3,1]]
)

# A[0,0:A.shape[0]]
eigVals, eigVect = practical_qr_algorithm(A,20,1e-5)
print(eigVals)
print(eigVect)
print('\n\nNP Results')
npr = np.linalg.eig(A)
print(npr[0])
print(npr[1])

# j=2
# print(A[:j,:j])
# print(A[j:,j:])

[[1 2 3 4]
 [2 1 2 2]
 [3 2 1 3]
 [4 2 3 1]] [[ 1.          0.          0.          0.        ]
 [ 0.         -0.37139068 -0.69098016 -0.62017367]
 [ 0.         -0.55708601 -0.36852275  0.74420841]
 [ 0.         -0.74278135  0.62188214 -0.24806947]]
eigenvect
[[-0.39830857  0.17177731  0.88495203  0.16941882]
 [ 0.91725148  0.07459282  0.38428282  0.07356867]
 [ 0.         -0.40349755  0.24698761 -0.88101467]
 [ 0.          0.89561052 -0.09046401 -0.43554342]]
eigenvect
[[ 0.58802149 -0.14339752 -0.79214776 -0.07854815]
 [-0.75590435 -0.1400585  -0.49569606 -0.40407629]
 [-0.28781824  0.07487366 -0.31652302  0.90075956]
 [ 0.         -0.97683914  0.16309669  0.13850908]]
eigenvect
[[-0.56377128  0.14652816  0.80860439  0.08276711]
 [ 0.82295889  0.10297658  0.54073943  0.14048262]
 [ 0.06961016 -0.13457484  0.17254265 -0.97327954]
 [ 0.00741921  0.97458449 -0.15488335 -0.16168231]]
eigenvect
[[ 0.5665005  -0.14604926 -0.80692416 -0.08136464]
 [-0.77192897 -0.13588496 -0.4772737  -0.397