In [1]:
import numpy as np

In [10]:
# for inspiration, this will be similar to full hessenberg
def fullHessenberg(matrix):
    A=matrix.copy().astype(float)
    m = A.shape[0]
    Q=np.identity(A.shape[0])

    for k in range(m-2):
        x=A[k+1:m,k]
        v = _getSign(x[0])*np.linalg.norm(x,2)*_getE1(x.shape[0]) + x
        v = v/np.linalg.norm(v,2)

        q_k=_getHV(v)
        P=np.identity(A.shape[0])
        P[k+1:,k+1:] = q_k
        Q=np.matmul(Q,P)

        A[k+1:m,k:m]=A[k+1:m,k:m]-2*np.outer(v,np.matmul(v,A[k+1:m,k:m]))
        A[0:m,k+1:m]=A[0:m,k+1:m]-2*np.outer(np.matmul(A[0:m,k+1:m],v.T),v)   
    return(A.round(8),Q)

def _getHV(v):
    I=np.identity(v.shape[0])
    return(I-2*np.outer(v,v))

# function that returns an e1 vector of length m
def _getE1(m):
    e1=np.zeros((m))
    e1[0]=1
    return(e1)

# a sign function that checks and corrects for x=0 according to notes in book
def _getSign(x):
    sign=np.sign(x)
    if sign==0: sign=1
    return(sign)

In [20]:
A = np.random.randint(10,size=(6,4))
A

array([[8, 6, 6, 7],
       [8, 2, 1, 2],
       [3, 2, 8, 7],
       [4, 7, 7, 7],
       [9, 0, 6, 6],
       [3, 2, 6, 5]])

In [21]:
k=0
x=A[k:,k]
u = _getSign(x[0])*np.linalg.norm(x,2)*_getE1(x.shape[0]) + x
u = u/np.linalg.norm(u,2)

A[k:,k:]=A[k:,k:]-2*np.outer(u,np.matmul(u,A[k:,k:]))
A

array([[-15,  -6, -11, -12],
       [  0,  -2,  -4,  -4],
       [  0,   0,   5,   4],
       [  0,   4,   4,   3],
       [  0,  -4,   0,  -1],
       [  0,   0,   3,   2]])

In [22]:
k=0
x=A[k,k+1:]
v = _getSign(x[0])*np.linalg.norm(x,2)*_getE1(x.shape[0]) + x
v = v/np.linalg.norm(v,2)

# A[k:,k:]=A[k:,k:]-2*np.outer(v,np.matmul(v,A[k:,k:]))
A[:,k+1:]=A[:,k+1:]-2*np.outer(np.matmul(A[:,k+1:],v.T),v) 
A

array([[-15,  17,   0,   0],
       [  0,   5,   0,   0],
       [  0,  -5,   2,   0],
       [  0,  -5,   0,  -2],
       [  0,   2,   2,   2],
       [  0,  -3,   1,   0]])